"""init schema

Revision ID: 90550f2cc91f
Revises: 
Create Date: 2025-08-13 11:37:34.055267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90550f2cc91f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('position', sa.String(length=120), nullable=False),
    sa.Column('resume_path', sa.String(length=512), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('career_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_career_applications_email'), ['email'], unique=False)

    op.create_table('service_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('contact_person', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('service_type', sa.String(length=80), nullable=False),
    sa.Column('timeline', sa.String(length=120), nullable=False),
    sa.Column('project_description', sa.Text(), nullable=False),
    sa.Column('budget_range', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_requests_email'), ['email'], unique=False)

    op.create_table('training_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_title', sa.String(length=200), nullable=False),
    sa.Column('application_date', sa.Date(), nullable=False),
    sa.Column('course_code', sa.String(length=80), nullable=False),
    sa.Column('course_start_date', sa.Date(), nullable=False),
    sa.Column('course_end_date', sa.Date(), nullable=False),
    sa.Column('applicant_name', sa.String(length=160), nullable=False),
    sa.Column('sex', sa.String(length=20), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('nationality', sa.String(length=100), nullable=False),
    sa.Column('passport_id', sa.String(length=80), nullable=False),
    sa.Column('date_of_issue', sa.Date(), nullable=False),
    sa.Column('employer', sa.String(length=200), nullable=False),
    sa.Column('contact_address', sa.Text(), nullable=False),
    sa.Column('emergency_contact', sa.Text(), nullable=False),
    sa.Column('education_background', sa.Text(), nullable=False),
    sa.Column('present_position', sa.String(length=160), nullable=False),
    sa.Column('present_post_date', sa.Date(), nullable=False),
    sa.Column('present_duties', sa.Text(), nullable=False),
    sa.Column('course_reason', sa.Text(), nullable=False),
    sa.Column('special_request', sa.Text(), nullable=True),
    sa.Column('course_info_source', sa.String(length=200), nullable=False),
    sa.Column('sponsorship', sa.String(length=20), nullable=True),
    sa.Column('sponsoring_agent', sa.String(length=200), nullable=True),
    sa.Column('sponsoring_address', sa.String(length=300), nullable=True),
    sa.Column('contact_person_title', sa.String(length=120), nullable=True),
    sa.Column('contact_person_name', sa.String(length=160), nullable=True),
    sa.Column('contact_person_phone', sa.String(length=40), nullable=True),
    sa.Column('contact_person_email', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_applications')
    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_requests_email'))

    op.drop_table('service_requests')
    with op.batch_alter_table('career_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_career_applications_email'))

    op.drop_table('career_applications')
    # ### end Alembic commands ###
