from marshmallow import Schema, fields, validate

class ServiceRequestSchema(Schema):
    companyName = fields.Str(required=True, validate=validate.Length(min=2, max=200))
    contactPerson = fields.Str(required=True, validate=validate.Length(min=2, max=160))
    email = fields.Email(required=True)
    phone = fields.Str(required=True, validate=validate.Length(min=3, max=32))
    serviceType = fields.Str(required=True)
    timeline = fields.Str(required=True, validate=validate.Length(min=1, max=120))
    projectDescription = fields.Str(required=True)
    budgetRange = fields.Str(required=False, allow_none=True)

class CareerApplicationSchema(Schema):
    firstName = fields.Str(required=True, validate=validate.Length(min=2, max=100))
    lastName  = fields.Str(required=True, validate=validate.Length(min=2, max=100))
    email     = fields.Email(required=True)
    phone     = fields.Str(required=False, allow_none=True)
    position  = fields.Str(required=True, validate=validate.Length(min=2, max=120))
    message   = fields.Str(required=False, allow_none=True)
    resumePath = fields.Str(required=False)  # optional if sending a file

class TrainingApplicationSchema(Schema):
    courseTitle = fields.Str(required=True, validate=validate.Length(min=2, max=200))
    applicationDate = fields.Date(required=True)
    courseCode = fields.Str(required=True, validate=validate.Length(min=1, max=80))
    courseStartDate = fields.Date(required=True)
    courseEndDate = fields.Date(required=True)
    applicantName = fields.Str(required=True, validate=validate.Length(min=2, max=160))
    sex = fields.Str(required=True)
    dob = fields.Date(required=True)
    nationality = fields.Str(required=True, validate=validate.Length(min=2, max=100))
    passportId = fields.Str(required=True, validate=validate.Length(min=3, max=80))
    dateOfIssue = fields.Date(required=True)
    employer = fields.Str(required=True, validate=validate.Length(min=2, max=200))
    contactAddress = fields.Str(required=True)
    emergencyContact = fields.Str(required=True)
    educationBackground = fields.Str(required=True)
    presentPosition = fields.Str(required=True, validate=validate.Length(min=2, max=160))
    presentPostDate = fields.Date(required=True)
    presentDuties = fields.Str(required=True)
    courseReason = fields.Str(required=True)
    specialRequest = fields.Str(required=False, allow_none=True)
    courseInfoSource = fields.Str(required=True, validate=validate.Length(min=2, max=200))
    sponsorship = fields.Str(required=False, allow_none=True)
    sponsoringAgent = fields.Str(required=False, allow_none=True)
    sponsoringAddress = fields.Str(required=False, allow_none=True)
    contactPersonTitle = fields.Str(required=False, allow_none=True)
    contactPersonName = fields.Str(required=False, allow_none=True)
    contactPersonPhone = fields.Str(required=False, allow_none=True)
    contactPersonEmail = fields.Email(required=False, allow_none=True)

service_request_schema = ServiceRequestSchema()
career_schema = CareerApplicationSchema()
training_schema = TrainingApplicationSchema()
